apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  labels:
    app.kubernetes.io/name: clife
  name: ciliumconfig
spec:
  k8sServiceHost: "api-int.{{ .Values.cluster_name }}.gruveai.com"
  k8sServicePort: "6443"
  cluster:
    name: default
  securityContext:
    privileged: true
  ipam:
    mode: "cluster-pool"
    operator:
      clusterPoolIPv4PodCIDRList:
    {{- range .Values.pod_cidr }}
      - {{ . | quote }}
    {{ end }}
      clusterPoolIPv4MaskSize: 23
  cni:
    binPath: "/var/lib/cni/bin"
    confPath: "/var/run/multus/cni/net.d"
    # portmap is needed for supporting HostPort without KPR
    chainingMode: portmap
    exclusive: false
  prometheus:
    enabled: true
    serviceMonitor:
     enabled: true
  gatewayAPI:
    enabled: {{ .Values.gatewayAPI_enabled }}
  l2announcements:
    enabled: {{ .Values.l2announcements_enabled }}
  hubble:
    enabled: {{ .Values.hubble.enabled }}
    relay:
      enabled: {{ .Values.hubble.relay_enabled }}
    timescape:
      enabled: {{ .Values.hubble.timescape_enabled }}
    ui:
      enabled: {{ .Values.hubble.ui_enabled }}
  operator:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  sessionAffinity: true
  kubeProxyReplacement: true
  #####MASQUERADING CONFIG
  ##this is to enable eBPF routing mode otherwise Linux default routing mode is present, and also it implements BPF masquerading mode. default is IP4 masquerading.
  bpf:
    masquerade: {{ .Values.masquerade_enabled }}
    hostLegacyRouting: {{ .Values.hostRouting_enabled }}
  ##### by default it is enabled and to disable masquerading we have to put false for it
  enableIPv4Masquerade: {{ .Values.masquerade_enabled }}
  ipMasqAgent:
    enabled: {{ .Values.enable_masq_agent }}

  routing-mode: {{ .Values.routing_mode }}
  ipv4-native-routing-cidr:
  {{- range .Values.ipv4_routing_cidr }}
    - {{ . | quote }}
  {{ end }}
  ipv6-native-routing-cidr:
  {{- range .Values.ipv6_routing_cidr }}
    - {{ . | quote }}
  {{ end }}
  # avoid conflicts
  clusterHealthPort: 9940
  # OVN Kubernetes default port, firewalls may already be configured for it
  tunnelPort: 4789
  enterprise:
    featureGate:
      approved:
    {{- range .Values.features }}
      - {{ . }}
    {{ end }}
