apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: storage-cluster
  namespace: openshift-storage
spec:
  enableCephTools: true
  encryption: {}
  flexibleScaling: true
  hostNetwork: false
  manageNodes: true
  monPVCTemplate:
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 29Gi
      storageClassName: local-vol-mon
  storageDeviceSets:
    - name: ocs-deviceset
      count: 3
      replica: 1
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          volumeMode: Block
          resources:
            requests:
              storage: 90Gi   # adjust to match actual /dev/sdb2 size, must be <= partition size
          storageClassName: local-vol-odf
      placement: {}
      preparePlacement: {}
      resources: {}