apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-operator-secret-reader
  namespace: grafana-operator
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch