apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-pages

data:

  employee.html: |
    <html>
    <body>
    <h1>Employee Page</h1>
    <p>This is Employee service from Apache backend</p>
    <p style="color: red;">Customer FE access strictly prohibited</p>
    </body>
    </html>


  salary.html: |
    <html>
    <body>
    <h1>Salary Page</h1>
    <p>This is Salary service from Apache backend</p>
    <p style="color: red;">Customer  FE access strictly prohibited</p>
    </body>
    </html>

  customer.html: |
    <html>
    <body>
    <h1>Customers Page</h1>
    <p>This is customer page for customers</p>
    </body>
    </html>

  positions.html: |
    <html>
    <body>
    <h1>Positions Page</h1>
    <p>This is Positions service from Apache backend</p>
    <p style="color: red;">Customer FE access strictly prohibited</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-backend
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-backend
  template:
    metadata:
      labels:
        app: apache-backend
    spec:
      containers:
      - name: apache
        image: registry.access.redhat.com/ubi9/httpd-24
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: apache-pages
          mountPath: /var/www/html
      volumes:
      - name: apache-pages
        configMap:
          name: apache-config
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: demo-app
spec:
  selector:
    app: apache-backend
  ports:
  - port: 8080
    targetPort: 8080
