apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: demo-app
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
        location /employee {
          proxy_pass http://apache-service:8080/employee.html;
        }
        location /salary {
          proxy_pass http://apache-service:8080/salary.html;
        }
        location /positions {
          proxy_pass http://apache-service:8080/positions.html;
        }
        location /customer {
          proxy_pass http://apache-service:8080/customer.html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-frontend
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-frontend
  template:
    metadata:
      labels:
        app: company-frontend
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: company-fe
  namespace: demo-app
spec:
  selector:
    app: company-frontend
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: company-fe-route
  namespace: demo-app
spec:
  to:
    kind: Service
    name: company-fe
  port:
    targetPort: 8080
