apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  generation: 1
  name: monitoring
spec: {}
status:
  relatedObjects:
  - group: ""
    name: openshift-monitoring
    resource: namespaces
  - group: ""
    name: openshift-user-workload-monitoring
    resource: namespaces
  - group: monitoring.coreos.com
    name: ""
    resource: servicemonitors
  - group: monitoring.coreos.com
    name: ""
    resource: podmonitors
  - group: monitoring.coreos.com
    name: ""
    resource: prometheusrules
  - group: monitoring.coreos.com
    name: ""
    resource: alertmanagers
  - group: monitoring.coreos.com
    name: ""
    resource: prometheuses
  - group: monitoring.coreos.com
    name: ""
    resource: thanosrulers
  - group: monitoring.coreos.com
    name: ""
    resource: alertmanagerconfigs
  versions:
  - name: operator
    version: 4.19.40
