apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
type: Opaque
stringData:
  access_key_id: "<value from AWS_ACCESS_KEY_ID>"
  access_key_secret: "<value from AWS_SECRET_ACCESS_KEY>"
  bucketnames: "loki--c8f1cbf2-cda6-4398-a983-a4dd999c8dd5"
  endpoint: "https://rook-ceph-rgw-storage-cluster-cephobjectstore.openshift-storage.svc:443"
  region: "us-east-1"
