apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  storageClassName: storage-cluster-ceph-rbd
  size: 1x.extra-small
  storage:
    schemas:
      - effectiveDate: "2024-04-01"
        version: v13
    secret:
      name: logging-loki-s3
      type: s3
  tenants:
    mode: openshift-logging
