operators:
  - operator_name: local-storage-operator
    operator_channel: stable
    operator_namespace: openshift-local-storage
  - operator_name: cluster-logging
    operator_channel: stable-6.5
    operator_namespace: openshift-logging
  - operator_name: odf-operator
    operator_channel: stable-4.19
    operator_namespace: openshift-storage
