apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
type: Opaque
stringData:
  access_key_id: "M1MJCPY7P7YQVR3WL6PF"
  access_key_secret: "q9MJKAxOBmvWgeakLqimBuZWaacREszC7pDIVMWi"
  bucketnames: "loki--c8f1cbf2-cda6-4398-a983-a4dd999c8dd5"
  endpoint: "https://rook-ceph-rgw-storage-cluster-cephobjectstore.openshift-storage.svc:443"
  region: ""
