{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "data": {
                "BUCKET_HOST": "rook-ceph-rgw-storage-cluster-cephobjectstore.openshift-storage.svc",
                "BUCKET_NAME": "loki--c8f1cbf2-cda6-4398-a983-a4dd999c8dd5",
                "BUCKET_PORT": "443",
                "BUCKET_REGION": "",
                "BUCKET_SUBREGION": ""
            },
            "kind": "ConfigMap",
            "metadata": {
                "creationTimestamp": "2026-08-31T01:15:32Z",
                "deletionGracePeriodSeconds": 0,
                "deletionTimestamp": "2026-09-01T09:32:45Z",
                "finalizers": [
                    "objectbucket.io/finalizer"
                ],
                "labels": {
                    "bucket-provisioner": "openshift-storage.ceph.rook.io-bucket"
                },
                "name": "loki-bucket",
                "namespace": "openshift-logging",
                "ownerReferences": [
                    {
                        "apiVersion": "objectbucket.io/v1alpha1",
                        "blockOwnerDeletion": true,
                        "controller": true,
                        "kind": "ObjectBucketClaim",
                        "name": "loki-bucket",
                        "uid": "209b2cd4-3e17-4ca3-a385-c967ad0c1e95"
                    }
                ],
                "resourceVersion": "5925035",
                "uid": "c77e14d6-310e-4244-8f01-51d5713ccbee"
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": ""
    }
}